services:
  app:
    build: .
    ports:
      - "8081:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: testdb
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-prootpassword"]
      interval: 5s
      retries: 10
